# pyre-ignore-all-errors
def foo():
    a = 1

    def inner():
        a

